name: Erlang CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:

  build:

    runs-on: ubuntu-latest

    container:
      image: erlang:22.0.7

    steps:
    - uses: actions/checkout@v3
    - name: Compile
      run: ./bin.sh
    - name: Run tests
      run: erl -pa . -noshell -s mysup start_link -s gen_server cast command ok
